#!/bin/bash
set -e

FBBINDGEN=./fbbindgen

rm -rf test/r
mkdir test/r

runtest() {
    headerfile="$1"
    echo "$headerfile..."
    $FBBINDGEN test/$headerfile -target   i686-pc-linux-gnu > test/r/$headerfile.linux_x86.bi
    $FBBINDGEN test/$headerfile -target x86_64-pc-linux-gnu > test/r/$headerfile.linux_x86_64.bi
    $FBBINDGEN test/$headerfile -target    i686-w64-mingw32 > test/r/$headerfile.win32.bi
    $FBBINDGEN test/$headerfile -target  x86_64-w64-mingw32 > test/r/$headerfile.win64.bi
}

for i in test/*.h; do
    runtest "${i#test/}"
done
